name: Dart CI

on:
  push:
    branches: [main, master, develop, feature/*]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Debug - List Directory Contents
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "JaeHyeok directory contents:"
          ls -la JaeHyeok/
          echo "hello-ci directory contents:"
          ls -la JaeHyeok/hello-ci/
      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - name: Get dependencies
        run: dart pub get
        working-directory: JaeHyeok/hello-ci
      - name: Run Hello Dart
        run: dart run hello.dart
        working-directory: JaeHyeok/hello-ci